development:
  adapter: async

test:
  adapter: async

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: Dischord_production

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: Dischord_production
